name: Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install --force

    - name: Run eslint
      run: npm run lint:ts
      if: always()

    - name: Run stylelint
      run: npm run lint:scss
      if: always()

    - name: Run jest
      run: npm run test:unit
      if: always()
