name: Deploy_storybook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build project
      run: npm run storybook:build

    - name: Install Netlify CLI
      run: npm install netlify-cli -g

    - name: Get last commit message
      id: commit
      run: echo "::set-output name=message::$(git log --format=%B -n 1)"

    - name: Deploy to Netlify
      run: netlify deploy --dir=storybook-static --prod --message "${{ steps.commit.outputs.message }}"
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

    